# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-04 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200504_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
        migrations.AlterField(
            model_name='post',
            name='CIN',
            field=models.IntegerField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='post',
            name='CNE',
            field=models.IntegerField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='post',
            name='Date_de_naissance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='Téléphone',
            field=models.IntegerField(default='SOME STRING', max_length=140),
        ),
    ]
