# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-04 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200504_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiche_de_condidature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=140)),
                ('prenom', models.CharField(default='', max_length=140)),
                ('CIN', models.IntegerField(default='', max_length=140)),
                ('CNE', models.IntegerField(default='', max_length=140)),
                ('Téléphone', models.IntegerField(default='', max_length=140)),
                ('Lieu_de_naissance', models.CharField(default='', max_length=140)),
                ('Date_de_naissance', models.DateField()),
                ('Adresse_physique', models.CharField(default='', max_length=140)),
                ('Sexe', models.CharField(default='', max_length=140)),
                ('Nationalité', models.CharField(default='', max_length=140)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
