# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-04 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200504_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche_de_condidature',
            name='CIN',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='fiche_de_condidature',
            name='CNE',
            field=models.CharField(default='', max_length=140),
        ),
    ]
