# Generated by Django 2.0 on 2020-05-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200504_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche_de_condidature',
            name='Téléphone',
            field=models.IntegerField(default=''),
        ),
    ]
