# Generated by Django 2.1.5 on 2020-05-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiche_de_condidature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=140)),
                ('prenom', models.CharField(default='', max_length=140)),
                ('CIN', models.CharField(default='', max_length=140)),
                ('CNE', models.CharField(default='', max_length=140)),
                ('Téléphone', models.IntegerField(default='')),
                ('Lieu_de_naissance', models.CharField(default='', max_length=140)),
                ('Date_de_naissance', models.DateField()),
                ('Adresse_physique', models.CharField(default='', max_length=140)),
                ('Sexe', models.CharField(default='', max_length=140)),
                ('Nationalité', models.CharField(default='', max_length=140)),
                ('pdf', models.FileField(upload_to='fiches/pdfs/')),
            ],
        ),
    ]
