# Generated by Django 2.1.5 on 2020-06-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20200604_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=140)),
                ('prenom', models.CharField(default='', max_length=140)),
                ('CIN', models.CharField(default='', max_length=140)),
                ('Lieu_de_naissance', models.CharField(default='', max_length=140)),
                ('Date_de_naissance', models.DateField()),
                ('Adresse_physique', models.CharField(default='', max_length=140)),
                ('Sexe', models.CharField(default='', max_length=140)),
                ('Nationalité', models.CharField(default='', max_length=140)),
                ('pdf', models.FileField(upload_to='fiches/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(default='', max_length=140)),
                ('Téléphone', models.IntegerField(default='')),
                ('Adresse_physique', models.CharField(default='', max_length=140)),
                ('Email', models.CharField(default='', max_length=140)),
                ('pdf', models.FileField(upload_to='fiches/pdfs/')),
            ],
        ),
    ]
