# Generated by Django 2.1.5 on 2020-06-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_carte_recu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carte',
            name='Date_de_naissance',
        ),
    ]
